---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp
  labels:
    app: bankingapp
spec:
  template:
    metadata:
      labels:
        app: bankingapp
    spec:
      containers:
      - name: bankingapp
        image: vootlasaicharan/bankingapp:4
        ports:
        - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: bankingapp
